### ISSUE TITLE
Ignore Block/Evade/Counter

### ISSUE THREAD

**Issue by ianbeard0159** [ianbeard0159/RPG_Project_Unity#13]
Attacks should have the option to ignore the targets defensive options.

**Comment by foldsters** [comment]
@ianbeard0159  Do we want the defense ignore calculation to be a 2D chance or a strict boolean check?

**Comment by foldsters** [comment]
Pushed a new branch. 

I made it chance based in the attack, and have `DealDamage` roll 2D and return 1, 0.5, or 0 depending on how many rolls the chance beats. 

Then `TakeDamage` checks to see if `ignoreDefense == 1` to see if both rolls were beaten and forces the damage to be taken, but that can be changed to `ignoreDefense > 0` if only one roll needs to be beaten. Not sure which way that should lean.

**Comment by ianbeard0159** [comment]
My idea was that some attacks simply ignore certain kinds of defense. For example, when fighting an enemy with a particularly high evasion rate, it would be useful for players to have attacks that ignore evasion chance.

I feel like the point is to offer the player a way to reduce the randomness of enemy defense at the expense of dealing less damage than they would with an ordinary attack. Therefore, adding an RNG element to the ignore defense calculation seems a bit counterproductive.

Also, I don't get GitHub notifications on my phone. It's probably good to post questions here like this, just ping me on discord too so that I'll see it sooner.

**Comment by foldsters** [comment]
Gotcha, I'll make changes later today.

**Comment by foldsters** [comment]
Should there be an ignore flag for evade, block, and counter separately or one ignoreDefense flag? 

I'm thinking just having 3 boolean flags called `evadable`, `blockable`, and `counterable` in the attack that get forwarded through DamageDealt into the TakeDamage function.

**Comment by ianbeard0159** [comment]
Yes, that's the general idea. Also, these flags should be set in the Unity Editor. (If you don't know, a public variable with no defined get/set method or a [SerializedField] will show up in the editor) 

Also, it might be better to make the flags ingoreEvade, ignoreCounter, and ignoreEvade. That way, it's clear to the person designing the attacks in the editor that the default behavior is that attacks do not ignore any defenses

**Comment by foldsters** [comment]
Merged into master by Ian
